/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiDocumentsUploadRouteImport } from './routes/api/documents/upload'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthDevRouteImport } from './routes/api/auth/dev'
import { Route as ApiThreadsThreadIdChatRouteImport } from './routes/api/threads/$threadId/chat'
import { Route as ApiDocumentsDocumentIdFileRouteImport } from './routes/api/documents/$documentId/file'
import { Route as ApiAuthGoogleStartRouteImport } from './routes/api/auth/google/start'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google/callback'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsUploadRoute = ApiDocumentsUploadRouteImport.update({
  id: '/api/documents/upload',
  path: '/api/documents/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthDevRoute = ApiAuthDevRouteImport.update({
  id: '/api/auth/dev',
  path: '/api/auth/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThreadsThreadIdChatRoute = ApiThreadsThreadIdChatRouteImport.update({
  id: '/api/threads/$threadId/chat',
  path: '/api/threads/$threadId/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsDocumentIdFileRoute =
  ApiDocumentsDocumentIdFileRouteImport.update({
    id: '/api/documents/$documentId/file',
    path: '/api/documents/$documentId/file',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthGoogleStartRoute = ApiAuthGoogleStartRouteImport.update({
  id: '/api/auth/google/start',
  path: '/api/auth/google/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/api/auth/google/callback',
  path: '/api/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/documents/$documentId/file': typeof ApiDocumentsDocumentIdFileRoute
  '/api/threads/$threadId/chat': typeof ApiThreadsThreadIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/documents/$documentId/file': typeof ApiDocumentsDocumentIdFileRoute
  '/api/threads/$threadId/chat': typeof ApiThreadsThreadIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/api/auth/dev': typeof ApiAuthDevRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/documents/upload': typeof ApiDocumentsUploadRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/google/start': typeof ApiAuthGoogleStartRoute
  '/api/documents/$documentId/file': typeof ApiDocumentsDocumentIdFileRoute
  '/api/threads/$threadId/chat': typeof ApiThreadsThreadIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/documents/$documentId'
    | '/api/auth/dev'
    | '/api/auth/signout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/documents/upload'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/documents/$documentId/file'
    | '/api/threads/$threadId/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/documents/$documentId'
    | '/api/auth/dev'
    | '/api/auth/signout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/documents/upload'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/documents/$documentId/file'
    | '/api/threads/$threadId/chat'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/health'
    | '/documents/$documentId'
    | '/api/auth/dev'
    | '/api/auth/signout'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/webhook'
    | '/api/documents/upload'
    | '/api/auth/google/callback'
    | '/api/auth/google/start'
    | '/api/documents/$documentId/file'
    | '/api/threads/$threadId/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  ApiAuthDevRoute: typeof ApiAuthDevRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiDocumentsUploadRoute: typeof ApiDocumentsUploadRoute
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
  ApiAuthGoogleStartRoute: typeof ApiAuthGoogleStartRoute
  ApiDocumentsDocumentIdFileRoute: typeof ApiDocumentsDocumentIdFileRoute
  ApiThreadsThreadIdChatRoute: typeof ApiThreadsThreadIdChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/upload': {
      id: '/api/documents/upload'
      path: '/api/documents/upload'
      fullPath: '/api/documents/upload'
      preLoaderRoute: typeof ApiDocumentsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/dev': {
      id: '/api/auth/dev'
      path: '/api/auth/dev'
      fullPath: '/api/auth/dev'
      preLoaderRoute: typeof ApiAuthDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/threads/$threadId/chat': {
      id: '/api/threads/$threadId/chat'
      path: '/api/threads/$threadId/chat'
      fullPath: '/api/threads/$threadId/chat'
      preLoaderRoute: typeof ApiThreadsThreadIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$documentId/file': {
      id: '/api/documents/$documentId/file'
      path: '/api/documents/$documentId/file'
      fullPath: '/api/documents/$documentId/file'
      preLoaderRoute: typeof ApiDocumentsDocumentIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/start': {
      id: '/api/auth/google/start'
      path: '/api/auth/google/start'
      fullPath: '/api/auth/google/start'
      preLoaderRoute: typeof ApiAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/api/auth/google/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiHealthRoute: ApiHealthRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  ApiAuthDevRoute: ApiAuthDevRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiDocumentsUploadRoute: ApiDocumentsUploadRoute,
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
  ApiAuthGoogleStartRoute: ApiAuthGoogleStartRoute,
  ApiDocumentsDocumentIdFileRoute: ApiDocumentsDocumentIdFileRoute,
  ApiThreadsThreadIdChatRoute: ApiThreadsThreadIdChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
